version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: heroes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroes_factory
      MYSQL_USER: heroes_user
      MYSQL_PASSWORD: heroes_pass
    ports:
      - "3306:3306"
    volumes:
      - heroes_data:/var/lib/mysql

volumes:
  heroes_data: